### ISSUE TITLE
Compile Error on Windows

### ISSUE THREAD

**Issue by BorisWiegand** [mrapp-ke/Boomer#1]
Hello,

I get the following compiling error on Windows when executing "make compile":
error C2664: "PredictionCandidate::PredictionCandidate(const PredictionCandidate &)" : Konvertierung von Argument 2 von "__pyx_t_6boomer_6common_7_arrays_uint32 *" in "uint32 *" nicht möglich
boomer\common\head_refinement.cpp(4162): note: Die Typen, auf die verwiesen wird, sind nicht verknüpft; die Konvertierung erfordert einen reinterpret_cast-Operator oder eine Typumwandlung im C- oder Funktionsformat.
boomer\python\boomer\common\cpp/predictions.h(64): note: Siehe Deklaration von "PredictionCandidate::PredictionCandidate"
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Do you have any idea how to fix this? 

Thank you very much in advance.

Kind regards

Boris Wiegand

**Comment by mrapp-ke** [comment]
Hello,

thank you for reporting this issue.

At first sight, this seems to be a platform/compiler-dependent issue to me. The current master branch compiles successfully on my Linux system (using GCC 10.2.0).

The compile error occurs in a part of the code that is written in Cython, but uses C++ code internally. The project includes type definitions of commonly used primitive data types for code that is written in Cython (in [`python/boomer/common/_arrays.pxd`](https://github.com/mrapp-ke/Boomer/blob/master/python/boomer/common/_arrays.pxd)) and C++ (in [`python/boomer/common/cpp/arrays.h`](https://github.com/mrapp-ke/Boomer/blob/master/python/boomer/common/cpp/arrays.h)), respectively. On your system the Cython/C++ definitions of the type `uint32` seem to be incompatible, most probably because they differ in the number of bits used.

For the C++ code, the type `uint32` is defined as
```
#include <cstdint>
...
typedef uint32_t uint32;
```
where `uint32_t` should be a 32 bit unsigned integer on all platforms (according to https://en.cppreference.com/w/cpp/header/cstdint).

For the Cython code, the definition is
```
cimport numpy as npc
...
ctypedef npc.uint32_t uint32
```
and therefore depends on what numpy is using internally. However, in https://numpy.org/doc/stable/user/basics.types.html it is stated that numpy's `uint32_t` type should be a 32 bit unsigned integer as well, regardless of the platform.

Based on the mentioned links, I would expect things to work, but apparently they are not. To tackle this issue it would be useful to know the exact representation of the C++/Cython data types on your Windows system. 

Please find attached a small program ([TypeTest.zip](https://github.com/mrapp-ke/Boomer/files/5689366/TypeTest.zip)) that you can compile and run to output the size of the individual data types.

For compilation, run the following commands:
```
make venv
make compile
make install
```
Afterwards, start the program:
```
venv/bin/python3 python/main.py
```
On my system the output is as follows:
```
C++ data types:

uint8: 1 bytes
uint32: 4 bytes
uint64: 8 bytes
intp: 8 bytes
float32: 4 bytes
float64: 8 bytes

Cython data types:

uint8: 1 bytes
uint32: 4 bytes
intp: 8 bytes
float32: 4 bytes
float64: 8 bytes
```
I would expect that the size of the C++/Cython types differ on your system, which would be an explaination of the problem you encountered.

**Comment by BorisWiegand** [comment]
Thank you for your fast response. Unfortunately, my output looks identical to yours:

```
C++ data types:

uint8: 1 bytes
uint32: 4 bytes
uint64: 8 bytes
intp: 8 bytes
float32: 4 bytes
float64: 8 bytes

Cython data types:

uint8: 1 bytes
uint32: 4 bytes
intp: 8 bytes
float32: 4 bytes
float64: 8 bytes
```

A colleague of mine was able to compile your code on his Linux system, so it is definitely an issue of my system.

**Comment by mrapp-ke** [comment]
Thanks for running this small sanity check. Seems like my assumptions were wrong. Unfortunately, I am out of ideas right now and I currently don't have a Windows system at hand to test things.

**Comment by BorisWiegand** [comment]
I edited the .cpp files manually by adding the necessary cast, e.g. (uint32 *), at every place the compiler complained.  Then, I could run make compile and make install. The library seems to work. I do not know if this has any side effects but at least it runs.

**Comment by BorisWiegand** [comment]
In the latest release (0.4.0), this is no longer an issue. However, I cannot make the code run on a Windows system. "make compile" fails. Meson and Ninja seem to run fine, but "python setup.py build_ext --inplace" fails:

`
warning: I don't know what to do with 'runtime_library_dirs': ['cpp/build/subprojects/common', 'cpp/build/subprojects/boosting']
error: don't know how to set runtime library search path for MSVC
`

Removing the parameter "runtime_library_dirs" also does not work and leads to another error:

`
LINK : fatal error LNK1181: Eingabedatei "mlrlcommon.lib" kann nicht geöffnet werden.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
`

From one of your former comments, I conclude that Windows is not a target platform of your development. Still I wanted to report this, in case other people are facing the same problem.

**Comment by mrapp-ke** [comment]
> `warning: I don't know what to do with 'runtime_library_dirs': ['cpp/build/subprojects/common', 'cpp/build/subprojects/boosting'] error: don't know how to set runtime library search path for MSVC`

This seems to be general Python issue on Windows (https://bugs.python.org/issue2437). Removing 'runtime_library_dirs' should not affect compilation, but is only relevant when running the program.

> Removing the parameter "runtime_library_dirs" also does not work and leads to another error:
> 
> `LINK : fatal error LNK1181: Eingabedatei "mlrlcommon.lib" kann nicht geöffnet werden. error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181`

Does this error occur when executing `make compile`? Or does compilation work, but the error is thrown when running the program? Is the file "mlrlcommon.lib" available in the directory "cpp/build/subprojects/common/" after compilation of the C++ code via Meson is done?

> From one of your former comments, I conclude that Windows is not a target platform of your development. Still I wanted to report this, in case other people are facing the same problem.

Yes, development exclusively takes place on Linux. But in the long run, the goal is to provide pre-compiled packages for Windows as well.

**Comment by BorisWiegand** [comment]
> Does this error occur when executing `make compile`? Or does compilation work, but the error is thrown when running the program? Is the file "mlrlcommon.lib" available in the directory "cpp/build/subprojects/common/" after compilation of the C++ code via Meson is done?

This happens during `make compile`, more precisely during `python setup.py build_ext --inplace`.

The file "mlrlcommon.lib" is indeed not available in "cpp/build/subprojects/common/". This is the content of the directory:
- libmlrlcommon-0.dll.p
- libmlrlcommon-0.dll
- libmlrlcoomon.dll.a

I have never used ninja or meson before, so it is completely unclear to me, why the ".lib" is not created by ninja and meson but demanded later by cython.

**Comment by mrapp-ke** [comment]
I think the meson build works fine. It compiles the C++ code as a dynamic shared library (`*.so` files on Linux, `*.dll` files on Windows). The problem is that the MSVC compiler demands for a `.lib` file, i.e., for a static library, to link against when building the Cython code.

**Comment by BorisWiegand** [comment]
What does that imply for fixing the problem? Should/can we tell Meson to create a .lib, should/can we tell msvc triggered by setup.py to accept *.dll or is this an open issue we cannot solve that easily?

**Comment by michael-rapp** [comment]
I think the correct way would be to tell the compiler that it should use *.dll files. But I don't know how this can be achieved.

**Comment by BorisWiegand** [comment]
Me neither. I have tried out a few things but could not find anything helpful to solve the problem.

**Comment by mrapp-ke** [comment]
It required a lot of effort, but since the latest version 0.8.0 the project can successfully be compiled on Windows (using the MSVC compiler). We also provide pre-built packages for Windows on [PyPI](https://pypi.org/project/mlrl-boomer/).
