### ISSUE TITLE
Understanding rules and how they work

### ISSUE THREAD

**Issue by supermaxiste** [mrapp-ke/Boomer#7]
Hi,

first of all thank you for implementing BOOMER and a very easy to use API.

I'm currently using BOOMER on a dataset for which I'd like to explore rules and find interesting patterns. 
I would like to make sure to understand the meaning of rules. At the top of each `rule` file all the label are listed together with a series of values, for example:

```
{} => (label1 = -1.45, label2 = -1.45, label3 = -1.89, label3 = -1.94)
```

I'm not entirely sure if these values represent the starting value for each label considered, but that's what I assumed based on the rest of the file.

In the rest of the file rules are represented by a series of features bound by a threshold and how they affect a specific label, for example:

```
{feature1 <= 1.53 & feature2 <= 7.935 & feature3 <= 6.604 & feature4 <= 74.81 & feature5 <= 12.395 & feature6 <= 0.305 & feature7 <= 0.415 & feature8 <= 6.83} => (label1= -0.31)
```

If I understood the model correctly, when this rule applies, it has a negative contribution towards `label1`. By aggregating all rules that apply, a value is obtained (for each label) which can be either positive, zero or negative and the prediction is `1` for all values > 0 and `0` otherwise.

Thank you in advance for your reply!

Stefan

**Comment by mrapp-ke** [comment]
Hello Stefan,

we're glad that you enjoy using our algorithm.

> At the top of each rule file all the label are listed together with a series of values, for example:
> 
> ```
> {} => (label1 = -1.45, label2 = -1.45, label3 = -1.89, label3 = -1.94)
> ```
> 
> I'm not entirely sure if these values represent the starting value for each label considered, but that's what I assumed based on the rest of the file.

Your assumption is correct. We refer to the first rule as the "default rule". Unlike the remaining rules, it does not come with any conditions on features and therefore applies to any given example. For each label, it provides a "default prediction" or "starting value" if you want to say so. The prediction for a particular label is positive, if most examples are associated with the respective label, otherwise it is negative. The ratio between the number of examples that are associated with a label and those that are not affects the absolute size of the default prediction. Values that are farther away from zero indicate that the data is very unbalanced.

> In the rest of the file rules are represented by a series of features bound by a threshold and how they affect a specific label, for example:
> 
> ```
> {feature1 <= 1.53 & feature2 <= 7.935 & feature3 <= 6.604 & feature4 <= 74.81 & feature5 <= 12.395 & feature6 <= 0.305 & feature7 <= 0.415 & feature8 <= 6.83} => (label1= -0.31)
> ```
> 
> If I understood the model correctly, when this rule applies, it has a negative contribution towards `label1`.

Again, your understanding is correct. Unlike the default rule, the remaining rules do only apply to examples that satisfy the rules' conditions. If a rule applies to an example, the example is said to be "covered" by the rule. In this case, the rule assigns a positive or negative value to one or several labels. The number of labels to be considered by a rule is controllable via the parameter `head_type` (see https://mlrl-boomer.readthedocs.io/en/latest/quickstart/index.html#parameters). A positive value expresses a preference towards predicting the corresponding label as relevant. A negative value contributes towards predicting the label as irrelevant. The absolute size of the value corresponds to the weight of the rule's prediction. The larger the value, the stronger the impact of the respective rule, compared to other ones.

A more formal description of the rules is given in Section 2.2. "Multi-label Classification Rules" of our paper (see https://arxiv.org/pdf/2006.13346.pdf).

> By aggregating all rules that apply, a value is obtained (for each label) which can be either positive, zero or negative and the prediction is `1` for all values > 0 and `0` otherwise.

Yes, this is the default strategy used for prediction. It aims to optimize the Hamming loss measure. There is also another strategy for optimizing the Subset 0/1 loss. You can specify which strategy should be used via the parameter `predictor` (see https://mlrl-boomer.readthedocs.io/en/latest/quickstart/index.html#parameters). A description of both prediction strategies can be found in Section 4.3 "Prediction" of our paper (see https://arxiv.org/pdf/2006.13346.pdf).

There is also a probabilistic interpretation of the aggregated value that is obtained for an individual label and example: By default, the (label-wise) logistic loss function is used for training (see parameter `loss` in https://mlrl-boomer.readthedocs.io/en/latest/quickstart/index.html#parameters). In this case, the aggregated value can be viewed as log odds. Passing it through the logistic sigmoid function (https://en.wikipedia.org/wiki/Sigmoid_function) results in a value between 0 and 1 that corresponds to the probability that the respective label is relevant to the example at hand.

Does this answer you questions?

**Comment by supermaxiste** [comment]
You've covered everything I needed to know and I'm glad to hear that I was able to understand the general ideas of the model.

Thank you very much for the thorough answer :)

**Comment by mrapp-ke** [comment]
You're welcome! :)
